"""商城首页 E2E 编排用到的页面对象协议（避免 ``flows`` import ``ShopHomePage`` 循环依赖）。"""
from __future__ import annotations

from typing import Any, Protocol, Tuple

# 阶段结束回调见 ``flows.shop_home_flow`` 中的 ``PhaseEndHook`` 别名


class ShopHomeFlowPage(Protocol):
    """``run_shop_home_flow`` 及其子阶段对 ``page`` 的最小方法集。"""

    def ensure_mall_tab(self, settle: float = 1.2) -> bool: ...

    def tap_mall_kingkong_daily_baihuo_via_popup(self) -> bool: ...

    def swipe_mall_kingkong_category_list_down(
        self, times: int = 5, settle_sec: float = 5.0, *, first_screen_sec: float = 5.0
    ) -> None: ...

    def run_category_spec_add_verify_line_qty(
        self, *, random_pick: bool = False, log_prefix: str = "分类"
    ) -> bool: ...

    def leave_mall_category_to_mall_home(self) -> bool: ...

    def run_mall_list_filters_scroll_and_back_top(self) -> bool: ...

    def run_mall_product_detail_deep_flow(self) -> bool: ...

    def tap_floating_or_entry_cart(self) -> bool: ...

    def tap_top_back(self) -> bool: ...

    def tap_banner_area(self) -> bool: ...

    def read_cart_badge_digit(self): ...

    def tap_first_add_cart_on_home(self) -> bool: ...

    def handle_add_cart_followups(self) -> Tuple[bool, str]: ...

    def read_cart_badge_digit_expect_increase(
        self, before, *, min_delta: int = 1, wait_sec: float = 26.0, step_sec: float = 1.0
    ): ...
